### ISSUE TITLE
Cleanup the corpus

### ISSUE THREAD

**Issue by aviggiano** [crytic/fuzz-utils#47]
### Describe the desired feature

Sometimes, Echidna segfaults because, I would guess, some of the call sequences trigger an invalidate state on the tool.

It would be nice to somehow remove only the invalid tx and keep the previous ones that are not "corrupted"

This seems like a quick fix to the segfault problem, and could perhaps be fixed in https://github.com/crytic/echidna directly, so please lmk if I should open an issue there instead.

**Comment by tuturu-tech** [comment]
Could you elaborate on what you mean by "corrupted", or what the cause of these invalid tx might be?

fuzz-utils doesn't really process the calls for correctness in any way, but I suppose if the cause is a code update (e.g. a function no longer exists in the corpus, or its signature has changed) we could filter those out. Although there might not be too much benefit since the call sequence probably won't trigger an increase in coverage anymore, so I think it would be similar to discarding the entire sequence itself.
